[package]
name = "mush-embed"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://mush.javanile.org/manifest.html

[dependencies]
#console = "*"
build_info = "#develop"
## Implement support for
## console = "git https://github.com/javanile/mush.git develop packages/console"
